version: "3.8"
services:
  front-app:
    image: node:alpine3.10
    container_name: reformat-irn-front
    ports:
      - 3000:3000
    working_dir: /opt/app
    command: sh -c "npm install --no-update-notifier; npm start --no-update-notifier"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3002 -w tableau.json
    ports:
      - "3002:3002"
    volumes:
      - ./data:/data
    restart: always

  k6-smoke:
    image: loadimpact/k6:latest
    command:  run /k6-sample/smokeTest.js
    volumes:
      - ./k6-sample:/k6-sample
  k6-stress:
    image: loadimpact/k6:latest
    command: run /k6-sample/stressTest.js
    volumes:
      - ./k6-sample:/k6-sample
  k6-soak:
    image: loadimpact/k6:latest
    command: run /k6-sample/soakTest.js
    volumes:
      - ./k6-sample:/k6-sample
  k6-load:
    image: loadimpact/k6:latest
    command: run /k6-sample/loadTest.js
    volumes:
      - ./k6-sample:/k6-sample

